[websearch]
default = "allow"

[webfetch]
default = "allow"

[mcp.deepwiki]
default = "allow"

[mcp.gh-grep]
default = "allow"

[mcp.context7]
default = "allow"

[bash]
default = "allow"

prompt = ["rm *"]

deny = ["sudo *"]
